### ISSUE TITLE
OSHwi SVG missing

### ISSUE THREAD

**Issue by easyw** [hulkco/oshwi#1]
Hi,
very nice piece of artwork!

I'm playing a bit with it in FreeCAD and I would like to be able to import the PCB with my [StepUp tools](https://github.com/easyw/kicadStepUpMod)

I noticed that your PCB edge is discretized as a large amount of small segments... would it be possible to share the original outline SVG file that you used to create the PCB outline (based on BSplines I suppose)?
I would like to convert it to a simpler PCB edge, converting BSplines to Arcs and Lines, to be able to load your board in FreeCAD.

some reference here:
* [kicad-stepup-new-hack-the-sketcher](https://hackaday.io/project/27354-kicad-stepup-new-hack-the-sketcher)
* [kicad-stepup-script-hacks-mcad-world](https://hackaday.io/project/7926-kicad-stepup-script-hacks-mcad-world)

Thanks in advance
Maurice

**Comment by hulkco** [comment]
Hello Maurice, an apology for the delay, just finished organizing the folders, the artwor is at: [https://github.com/hulkco/oshwi/tree/master/2017/ArtWork](url)
I hope it serves you, I will proceed to close the isue.
Regards!
