### ISSUE TITLE
[Question] Capacitors on WS2812B 

### ISSUE THREAD

**Issue by thorgod** [hulkco/oshwi#2]
Question why is there only one capacitors connected to each VCC (VDD) on the WS2812B (Intelligent control LED)?

In the datasheet example each WS2812B (Intelligent control LED) has a capacitor attached to it. (https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf )

Looking to create a board for fun using your example. Also digikey seems kind of expensive to buy WS2812B like $4.50 USD an unit, did you get the LED from somewhere else?

**Comment by hulkco** [comment]
Hello, an apology for the delay, buy all the components in the Aliexpress page, I base myself on the designs of Adafruit, where they also use the same capacitor array, I hope it works for you, I will proceed to close the isue.

Regards!
